cloudpilot-ai/karpenter-provider-gcp

README.md

doc: update banner size

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/CLEANUP.md
.github/ISSUE_TEMPLATE/ENHANCEMENT.md
.github/ISSUE_TEMPLATE/SUPPORT.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/presubmit.yaml
README.md

chore: add issue and pr template

chore: add issue and pr template

---

cmd/controller/main.go
pkg/controllers/controllers.go
pkg/operator/operator.go

/kind feature
feat: support nodepooltemplate controller
Fixes #none
none
```release-note
```

feat: support nodepooltemplate controller

---

README.md

doc: add Discord link
Fixes #none
doc: add Discord link
```release-note
```

doc: add Discord link

---

OWNERS

doc: add repo approvers and reviewers
Fixes #none
```release-note
```

doc: add repo approvers and reviewers

---

CONTRIBUTING.md

doc: fix chapter layer
Fixes #
doc: fix chapter layer
```release-note
```

doc: fix chapter layer

---

CONTRIBUTING.md

Add a new GCP Role required for Karpenter to run.
None
We should split the required roles to create the GKE cluster and the roles required for Karpenter to run. If you agree, let me know and I can change this PR to do that 👍 .
```release-note
doc: add Compute Admin GCP Role to SA requirement
```

doc: add Compute Admin GCP Role to SA requirement

---

pkg/controllers/interruption/controller.go

/kind bug
Fixes #
Karpenter need register trigger by `For()`, `Owns()`, `Watches()` or `WatchesRawSource()` to set them up.
```release-note
fix panic in interruption controller.
```
cc @jwcesign @patrostkowski

fix: fix panic in interruption controller.

---

pkg/cache/cache.go
pkg/cloudprovider/cloudprovider.go
pkg/operator/operator.go
pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/types.go

Support to query instance type with liveness probe and 
/kind feature
Check the instance type and support the liveness probe function.
Fixes #
```release-note
Add instance type and liveness probe.
```

feat: add instance type and liveness probe.

---

cmd/controller/main.go
pkg/controllers/controllers.go
pkg/controllers/interruption/controller.go
pkg/operator/operator.go

/kind bug
Change operation from region operator to zone operator.
Fixes #
```release-note
fix: update region operation client to zone operation client.
```
cc @patrostkowski

fix: update region operation client to zone operation client.

---

pkg/providers/pricing/pricing.go

/kind feature
1. Add pricing cache in download function.
Fixes #
```release-note
fix: add pricing download cache.
```

fix: add pricing download cache.

---

examples/nodepool/default-nodepool.yaml
pkg/providers/instance/instance.go
pkg/providers/metadata/utils.go

/kind bug
fix: reduce long node deletion delay
Fixes #none
none
```release-note
```

fix: reduce long node deletion delay

---

pkg/providers/instance/instance.go

/kind cleanup
none
Fixes #none
```release-note
```

refactor: optimize instance retrieval by using cache-first approach and consolidating sync logic

---

pkg/cloudprovider/cloudprovider.go
pkg/providers/instance/instance.go

/kind cleanup
none
Fixes #none
```release-note
```

refactor: streamline instance creation by selecting the cheapest instance type

---

cmd/controller/main.go
pkg/controllers/controllers.go
pkg/controllers/interruption/controller.go
pkg/providers/instance/instance.go

/kind feature
Fixes #
```release-note
```

feat: handle terminated/stopped ins

---

pkg/providers/instance/instance.go

fix: run instance with the selected image

---

charts/karpenter/crds/karpenter.k8s.gcp_gcenodeclasses.yaml
pkg/apis/v1alpha1/gcenodeclass.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/operator/operator.go
pkg/providers/imagefamily/containeroptimizedos.go
pkg/providers/imagefamily/image.go
pkg/providers/imagefamily/types.go
pkg/providers/imagefamily/ubuntu.go
pkg/providers/instance/instance.go

feat: support image id

---

pkg/providers/imagefamily/image.go

Fixes #
```
env: dev
status:
conditions:
- lastTransitionTime: "2025-07-17T03:58:53Z"
message: ImageSelector did not match any Images
observedGeneration: 2
reason: ImagesNotFound
status: "False"
type: ImagesReady
- lastTransitionTime: "2025-07-17T03:58:53Z"
message: ImagesReady=False
observedGeneration: 2
reason: UnhealthyDependents
status: "Fals
```
```release-note
```

fix: throw error if the image not found

---

pkg/providers/instance/instance.go

chore: create node faster

---

pkg/providers/instancetype/types.go

feat: support gpu

---

pkg/controllers/providers/pricing/controller.go
pkg/providers/pricing/pricing.go
pkg/providers/pricing/pricing_test.go

chore: price provider cleanup

---

charts/README.md
charts/karpenter/.helmignore
charts/karpenter/Chart.yaml
charts/karpenter/templates/_helpers.tpl
charts/karpenter/templates/clusterrole-core.yaml
charts/karpenter/templates/clusterrole.yaml
charts/karpenter/templates/deployment.yaml
charts/karpenter/templates/poddisruptionbudget.yaml
charts/karpenter/templates/role.yaml
charts/karpenter/templates/service.yaml
charts/karpenter/templates/serviceaccount.yaml
charts/karpenter/values.yaml

chore: add helm charts

---

.github/workflows/cloudpilot-latest-build.yaml

ci: add image build workflow

---

pkg/providers/instance/instance.go
pkg/providers/metadata/utils.go

fix: karpenter nodes not belongs to gke nodepool

---

charts/README.md

cleanup: typo fix

---

cmd/controller/main.go
examples/nodepool/default-nodepool.yaml
pkg/controllers/controllers.go
pkg/controllers/csr/csr.go
pkg/controllers/node/controller.go

Parts of https://github.com/cloudpilot-ai/karpenter-provider-gcp/issues/93
```release-note
```

feat: delete empty nodes

---

charts/karpenter/values.yaml

chore: add resource request and anti affinity

---

pkg/cloudprovider/cloudprovider.go
pkg/providers/instance/instance.go
pkg/utils/utils.go

/kind cleanup
Use cluster name to limit the query range
Fixes #none
Use cluster name to limit the query range
```release-note
```

fix: add clutser name labels to the vm created

---

pkg/controllers/interruption/controller.go

/kind bug
Just fired this up in our cluster, met with errors
```
handling spot interruption events: deleting node claim: getting node claim by node name: no nodeclaim found for node {existing node}
```
I think it should only be doing this for karpenter managed nodes, right?
Fixes #107 
```release-note
NONE
```

Check if node is handled by karpenter, not just if it's in the cluster

---

pkg/providers/instance/instance.go
pkg/providers/metadata/utils.go

/kind feature
This PR implements the max pods per node kubelet configuration
Fixes #111 
```release-note
This PR implements the max pods per node kubelet configuration. Fixes #111
```

Implement max pods configuration

---

charts/README.md

A clearer installation document
Fixes #none
none
```release-note
```

doc: make charts doc better

---

pkg/providers/instance/instance.go

feat/instance: add default cloud platform scopes to service accounts

---

charts/karpenter/crds/karpenter.k8s.gcp_gcenodeclasses.yaml
charts/karpenter/crds/karpenter.sh_nodeclaims.yaml
charts/karpenter/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1alpha1/gcenodeclass.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/nodeclass/hash/controller.go
pkg/providers/instance/instance.go
pkg/providers/metadata/utils.go

/kind cleanup
GCE supports two tags and labels, as follows:
What we implemented previously was GCE labels.
Fixes #none
chore: rename gce tags to gce labels
```release-note
```

chore: rename gce tags to gce labels

---

pkg/providers/instance/instance.go

/kind feature
Referring to: https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr
We should set correct network CIDR when creating pods.
Before:
```
Capacity:
cpu:                1
ephemeral-storage:  57549204Ki
hugepages-1Gi:      0
hugepages-2Mi:      0
memory:             3757872Ki
pods:               20
Allocatable:
cpu:                940m
ephemeral-storage:  9013931535
hugepages-1Gi:      0
hugepages-2Mi:      0
memory:             2672432Ki
pods:               20
System Info:
Machine ID:                 926668eb2f470e00b27a55b50f33b394
System UUID:                926668eb-2f47-0e00-b27a-55b50f33b394
Boot ID:                    c86d8394-16cd-4193-a5ca-1e0ff5496454
Kernel Version:             6.6.97+
OS Image:                   Container-Optimized OS from Google …
```

feat: support CIDR adjustment to be compatible with max pods
